config/routes.rb
YoutubeAgain::Application.routes.draw do
  resources :channels

  resources :users
 match '/search', to: 'users#search', via: 'get'
 match '/live_button', to: 'users#live_button', via: 'get'
 match '/signup',  to: 'users#new',            via: 'get'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = Channel.find(params[:id])

  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)
    Pusher['survey-channel'].trigger('data-changed', [@channel.name,@channel.message])
    if @channel.save
      respond_to do |format|
        format.html {redirect_to @channel}
        format.js
      end
      else
        render 'new'
      end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name, :message)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for :channel, :remote => true, url: channels_path do |f| %>
  

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Listing channels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= channel.message %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<%= render 'form' %>


    
    <div id="chatbox"></div>



<script src="http://js.pusherapp.com/2.2/pusher.min.js"></script>
<script>
$(function () {
    //establish Pusher connection
    var pusher = new Pusher('1e654b95cdf49ce5e092');
    var myChannel = pusher.subscribe('survey-channel');
    // deal with new messages
    myChannel.bind('data-changed', function(data){
      updateResults(data)
      console.log('was here');
    });
    
  });
  
  function updateResults(data){

	var oldscrollHeight = $("#chatbox").prop("scrollHeight") - 20; //Scroll height before the request


	var d = new Date();
	$("#chatbox").append("("+d.getHours()+":"+d.getMinutes()+":"+ d.getSeconds()+") "+data[0]+":"+data[1]);
	$("#chatbox").append("<br>");
    var newscrollHeight = $("#chatbox").prop("scrollHeight") - 20; //Scroll height after the request

    if( newscrollHeight > oldscrollHeight){
      $("#chatbox").animate({ scrollTop: newscrollHeight }, 'normal'); //Autoscroll to bottom of div
    } 
    
  
    //tbody.html(html);
    //jQuery(".chartscontainer").remove(); // remove old chart
    //jQuery("#results").charts(); // show updated chart
  }
</script>