config/routes.rb
YoutubeAgain::Application.routes.draw do
  resources :channels

  resources :users
 match '/search', to: 'users#search', via: 'get'
 match '/live_button', to: 'users#live_button', via: 'get'
 match '/signup',  to: 'users#new',            via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
validates :name, presence: true,length: { maximum: 50 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
				  uniqueness: {case_sensitive: false}
has_secure_password
validates :password, length: { minimum: 6 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  require 'rubygems'

require 'google/api_client'

 
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end


   def create
    @user = User.new(user_params)
     Pusher['survey-channel'].trigger('data-changed', [@user.name,@user.email])
    if @user.save
      respond_to do |format|
        format.html {redirect_to @user}
        format.js
      end
      else
        render 'new'
      end
  end
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @users= User.all
  end


  def live_button


  end

def search
    
    
    opts={}
    client, youtube = get_service
opts[:q] ='kings of cali mew2king'
opts[:max_results]=26
    begin
      # Call the search.list method to retrieve results matching the specified
      # query term.
      if params[:search]
        opts[:q] = "#{params[:search]}"
      end
          
      if params[:max_results]
        opts[:max_results]="#{params[:max_results]}"
      end

      @search_response = client.execute!(
        :api_method => youtube.search.list,
        :parameters => {
          :part => 'snippet',
          :q => opts[:q],
          :maxResults => opts[:max_results]
        }
      )

      @videos = []
      @channels = []
      @playlists = []
      @likes =[]
      # Add each result to the appropriate list, and then display the lists of
      # matching videos, channels, and playlists.
      @search_response.data.items.each do |search_result|
        case search_result.id.kind
          when 'youtube#video'
            @videos << "#{search_result.id.videoId}"
           
          when 'youtube#channel'
            @channels << "#{search_result.snippet.title} (#{search_result.id.channelId})"
          when 'youtube#playlist'
           @playlists << "#{search_result.snippet.title} (#{search_result.id.playlistId})"
        end
      end

      @like_response = client.execute!(
        :api_method => youtube.videos.list,
        :parameters => {
          :part => 'statistics',
          :id => "#{@videos.join(",")}"
        }
      )

      @like_response.data.items.each do |like_result|
            @likes << "#{like_result.statistics.likeCount}"
      end

     # puts "Videos:\n", videos, "\n"
      #puts "Channels:\n", channels, "\n"
      #puts "Playlists:\n", playlists, "\n"
    #rescue Google::APIClient::TransmissionError => e
     # puts e.result.body
    #end
    

    end
  end
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
 

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email,:password,:password_confirmation)
    end


    def get_service
  client = Google::APIClient.new(
    :key => DEVELOPER_KEY,
    :authorization => nil,
    :application_name => $PROGRAM_NAME,
    :application_version => '1.0.0'
  )
  youtube = client.discovered_api(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION)

  return client, youtube
end

DEVELOPER_KEY = 'AIzaSyCZgl9jnag2Nub8C7mj0rZWS332DyVey7o'
YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
 <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/users/create.js.erb
$("#user_table").append("<%= escape_javascript(render(:partial => @user)) %>");

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/live_button.html.erb
<!DOCTYPE html>
<html>
  <body>
    <!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
    <div id="player"></div>

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<script src="//js.pusher.com/2.2/pusher.min.js"></script>

<!-- Downloaded in step 1 -->
<script src="pusher-realtime-chat-widget/src/js/PusherChatWidget.js"></script>
<link href="pusher-realtime-chat-widget/src/pusher-chat.css" rel="stylesheet" type="text/css" />

    <script>
    






      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      var zoomAhead=0;
      function onYouTubeIframeAPIReady() {
        var e = new Date();
        var d = new Date(2014, 7, 21, 13, 9, 0, 0);
        console.log(e.getTime()-d.getTime());
        
        if(e.getTime()>d.getTime()){
          zoomAhead=Math.round((e.getTime()-d.getTime())/1000);
        }
        player = new YT.Player('player', {
          height: '390',
          width: '640',
          videoId: '21O9x8nYoqY',
          playerVars: { 'controls': 1,
          'start': zoomAhead },
          events: {
            'onReady': onPlayerReady,
          }
        });

      }
      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        var d = new Date(2014, 7, 21, 13, 9, 0, 0);
        console.log(d.getTime())
        var e = new Date();
        console.log(d.getTime()-e.getTime());
      	setTimeout(function() { event.target.playVideo();},0);
     
        
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
        	
         
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
    </script>
  </body>
</html>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/search.html.erb
<body>
<p> <%= "#{@likes}" %> </p>
    <!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
    <br>
<%= form_tag '/search', :method => 'get',:class=> "form-inline"   do %>
   <div class= "left">
    <%= label_tag(:search, "Search for:") %>
    <%= text_field_tag :search %>

    
    <%= radio_button_tag :max_results, 6 %>
    <%= label_tag(:top_6, "Top 6") %>

    <%= radio_button_tag(:max_results, 26) %>
    <%= label_tag(:top_26, "Top 26 (default)") %>
    
    
    <%= submit_tag "Search", :name => nil %>
  </div>
<% end %>
  <br>
<div id="output" class="out left">
    <script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var playerArray = new Array();
      function onYouTubeIframeAPIReady() {
        
        
        <% $i = 0%>
        <%begin%>
            var ele = document.createElement("div");
            ele.setAttribute("id","player"+"<%=$i%>");
            output.appendChild(ele);
            var ele2 = document.createElement("div");
            ele2.setAttribute("id","player"+"<%=$i+1%>");
            output.appendChild(ele2);

            var elem = document.createElement("div");
            elem.setAttribute("id","rating"+"<%=$i%>");
            elem.setAttribute("style", "top:" +  49 + "px; left:" + 30 + "px; width:" + 640 + "px; height:" + 42+ "px; display:"+ "table-cell");
            var t=document.createTextNode("Likes: <%=@likes[$i]%>");
            elem.appendChild(t);
            output.appendChild(elem);
            
            var elem2 = document.createElement("div");
            elem2.setAttribute("id","rating"+"<%=$i+1%>");
            elem2.setAttribute("style", "top:" +  49 + "px; left:" + 30 + "px; width:" + 640 + "px; height:" + 42+ "px; display:"+ "table-cell");
            var t=document.createTextNode("Likes: <%=@likes[$i+1]%>");
            elem2.appendChild(t);
            output.appendChild(elem2);

           
            var elem3 = document.createElement("br");
            output.appendChild(elem3);
            playerArray[<%=$i%>] = new YT.Player('player'+"<%=$i%>", {
              height: '390',
              width: '640',
              videoId: "<%= @videos[$i] %>",
              events: {
           
              }
            });

             playerArray[<%=$i+1%>] = new YT.Player('player'+"<%=$i+1%>", {
              height: '390',
              width: '640',
              videoId: "<%= @videos[$i+1] %>",
              events: {
           
           
              }
            });
            
            <% $i +=2%>
       
        <% end while $i < @videos.length%>
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        
        event.target.playVideo();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 6000);
          done = true;
        }
      }
      function stopVideo() {
        <% @videos.each_with_index do |video,i| %>
        playerArray[<%=i%>].stopVideo();
         <% end%>
      }
    </script>
  </body>

app/views/users/show.html.erb
<%= render 'form' %>


    
    <div id="chatbox"></div>


<table id ="user_table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<script src="http://js.pusherapp.com/2.2/pusher.min.js"></script>
<script>
$(function () {
    //establish Pusher connection
    var pusher = new Pusher('1e654b95cdf49ce5e092');
    var myChannel = pusher.subscribe('survey-channel');
    // deal with new messages
    myChannel.bind('data-changed', function(data){
      updateResults(data)
      console.log("here now");
    });
    console.log("now here");
  });
  
  function updateResults(data){
   $("#user_table").append(data[0]);
$("#user_table").append(data[1]);
var oldscrollHeight = $("#chatbox").prop("scrollHeight") - 20; //Scroll height before the request


var d = new Date();
$("#chatbox").append("("+d.getHours()+":"+d.getMinutes()+":"+ d.getSeconds()+") "+data[0]+":"+data[1]);
$("#chatbox").append("<br>");
        var newscrollHeight = $("#chatbox").prop("scrollHeight") - 20; //Scroll height after the request

        if(newscrollHeight > oldscrollHeight){
          $("#chatbox").animate({ scrollTop: newscrollHeight }, 'normal'); //Autoscroll to bottom of div
        } 
    
  
    console.log("was here");

    //tbody.html(html);
    //jQuery(".chartscontainer").remove(); // remove old chart
    //jQuery("#results").charts(); // show updated chart
  }
</script>